
version: '2'

services:
  screenshotter:
    build: .
    ports:
      - 8090:80
    environment:
      - PORT=80
      - DEBUG=1
    volumes:
      - ./dist:/code/dist
      - ./docker-entrypoint.sh:/code/docker-entrypoint.sh
      - ./test/tmp:/screenshots


